name: glob-changed-files-action
description: Action to expand glob patterns by changed files of pull request
inputs:
  paths:
    description: Glob patterns (multiline)
    required: true
  paths-fallback:
    description: Glob patterns to fallback (multiline)
    required: false
  transform:
    description: Paths to transform (multiline)
    required: false
  token:
    description: GitHub token to list the changed files
    required: true
    default: ${{ github.token }}
outputs:
  paths:
    description: List of the changed files (multiline)
  paths-json:
    description: List of the changed files (JSON)
runs:
  using: 'node20'
  main: 'dist/index.js'
